### ISSUE TITLE
Big Sur icon proposal

### ISSUE THREAD

**Issue by RickyRomero** [joelekstrom/fastmate#28]
Hi! If you haven't started on a Big Sur icon yet, I've mocked one up as a proposal. I haven't built out the assets for all the sizes and gamuts, but if you like this one then I'd be happy to finish and submit this as a PR. (I'm comfortable with Xcode.)

Let me know what you think, or if you have any changes to propose.

![fastmate-p3-1024-shadow](https://user-images.githubusercontent.com/233891/100552068-a94f4000-3239-11eb-968e-5ca7f64470a7.png)

**Comment by joelekstrom** [comment]
Hi! That looks terrific!

I’d be happy to add this to Fastmate (there likely won’t be a Big Sur icon for a long time otherwise because of my lack of design skills and patience 😬)

Thanks so much for taking the time

**Comment by joelekstrom** [comment]
I don’t have any changes to propose. Feel free to change things up if you have better ideas too!

**Comment by RickyRomero** [comment]
Gotcha, thanks for the feedback. I was wondering if you'd based your icon on an older version of the logo...

I was inspired by origami with this icon design, so... if you're concerned about getting a nasty letter from a lawyer, we could extend that origami metaphor... Maybe add some folds to the original shapes to make it look like a simple origami bird?

![image](https://user-images.githubusercontent.com/233891/100660410-d74e8600-3306-11eb-8d55-0d0ebe5c81b7.png)

Or, change the shapes to make it look more abstract while using the same color scheme and arrangement? Or I could just do what you did and add a third shape :-)

Is this design too close to the FastMail logo in your opinion? Would it be a dealbreaker if we went with it as is?

**Comment by RickyRomero** [comment]
Here's an alternative design to consider.

<img alt="fastmate-p3-1024-v2" src="https://user-images.githubusercontent.com/233891/100676285-79796880-331d-11eb-91ab-fdc927ceaf32.png">

**Comment by joelekstrom** [comment]
Hey, I really like the origami idea 😊 

I’m actually not sure how close you can go with logos. Maybe the shape in the middle is abstract enough to be considered OK to borrow. At least the circle around it isn’t there/different. But in the worst case we could just revert to another one if you choose to go with the proposed one and Fastmail doesn’t like it!

Maybe even someone from the Fastmail team has some input? cc @rjbs

**Comment by joelekstrom** [comment]
Ah, the second idea is really cool as well! Posted as I was typing so saw it too late 😬

**Comment by rjbs** [comment]
I think it looks great!  Also, you shouldn't use it.  😕

It's like this:  if somebody starts riffing on our logo to do something super shady, and we say stop, and they say "You didn't tell so-and-so to stop when *they* made a logo confusable with yours!" then we're in trouble, because you can't have a trademark if you don't defend it vigorously.  This is annoying for almost everybody involved except for the lawyers who make money no matter what.

So:  how do you make a logo that you feel is suitably evocative of what you're doing without any chance of it being confusable with an actual product of Fastmail?  Folks, I don't know, and I wish I could help.  I am not a designer by any means, just a guy who doesn't want to end up in an adversarial relationship with people who like his company's product!

**Comment by RickyRomero** [comment]
Thanks for your input @rjbs. I'll work with Joel directly on this.
