### ISSUE TITLE
Add Applescript support

### ISSUE THREAD

**Issue by mdbraber** [joelekstrom/fastmate#35]
In my forked version (https://github.com/joelekstrom/fastmate/issues/14) I previously integrated Applescript support to return current URL and title. As there's now also to Copy Link / Copy Fastmate URL there might be a better way. Would you be willing to include Applescript support in the main version? Some pointers might be in my (probably crudely done) forked version

**Comment by joelekstrom** [comment]
As with the other feature, I'd be happy to include it if you could provide a separated PR for it! I may not take the time to investigate and build a solution myself (since I don't personally have use for AppleScript), but I really appreciate any contributions, even if they could be considered crude. 😄

**Comment by mdbraber** [comment]
I have a PR ready to submit in the next few days enabling three simple commands: get current URL, get current title, execute arbitrary javascript.

**Comment by mdbraber** [comment]
https://github.com/joelekstrom/fastmate/pull/81/commits/2b64b1247cebd2d520064f746183dc9077a4e311
