### ISSUE TITLE
Combine branch status?

### ISSUE THREAD

**Issue by mdbraber** [joelekstrom/fastmate#56]
I'm still using my custom version of Fastmate everyday and enjoying it. I've recently been building a similar wrapper but for Todoist which I made in Swift. I saw you also created a 'combine' branch about a year ago using Swift. Do you (still) have any plans to port Fastmate from Obj-C to Swift?

**Comment by joelekstrom** [comment]
I do! I created that branch mostly to learn Combine, so it’s a bit problematic in the sense that it a probably “too reactive” since I deliberately tried to use it for pretty much everything to learn 😬 it does work though so feel free to fork that branch if that’s what you want.

However, take a look at the last few commits on master. I’ve started to slowly do a more sensible Swift rewrite. I pick the good parts from the Combine branch, but mostly try to do a 1-1 rewrite to Swift to keep changes minimal. When everything is migrated it’s easier to “Swiftify” stuff.

**Comment by mdbraber** [comment]
Great - nice to hear! Are you indeed planning on using something like Swiftify.com when the rewriting is done?

**Comment by joelekstrom** [comment]
No. I prefer to just rewrite it myself and improve where needed. With "Swiftify" I mean after migrating, changing to using stuff like Combine KVO publishers instead of the KVOBlockObserver it's currently using in objc

**Comment by joelekstrom** [comment]
😂 I'm sorry - I had forgotten to push the commits I talked about above. They are on master now...

**Comment by posguy99** [comment]
> I've recently been building a similar wrapper but for Todoist which I made in Swift. 

Not that it's related to Fastmate, but I looked on your Github page and didn't see a Todoist wrapper.  Are you doing anything that Todoist's own wrapper doesn't?

**Comment by mdbraber** [comment]
@posguy99 yes, I'm doing a native quick add window, support Applescript and integrate todoist-shortcuts to name a few. It's not ready for release yet, but works well already.
