### ISSUE TITLE
Notification count updates from open folder, not Inbox

### ISSUE THREAD

**Issue by iamscott** [joelekstrom/fastmate#6]
Notification should always show count of Inbox.

Alternatively, this could be added to a preferences dialog which allows user to select which count should be shown.

**Comment by joelekstrom** [comment]
This is an effect of how Fastmail displays the unread count in the browser tab (only selected folder). Fastmate currently keeps it simple by just extracting the number from the title.

For me personally, the current system works pretty well, since I select my work inbox when at work, and my normal inbox at home.

With that said, I like the idea of having a setting - maybe allowing the choice of current folder, all folders, or a specific folder where you can enter the folder name that should be observed. I’ll think about it for a bit

This would require Fastmate to be a bit more clever and parse the actual folder names and unread counts.

**Comment by joelekstrom** [comment]
Fixed in [1.1.0](https://github.com/joelekstrom/fastmate/releases/tag/v1.1.0), thanks for the suggestion!

**Comment by iamscott** [comment]
Thanks!!
