### ISSUE TITLE
Attached PDF printing not working

### ISSUE THREAD

**Issue by sddgit** [joelekstrom/fastmate#67]
When I click on a PDF attachment, it is displayed fine. But when I go to print, the page is blank, apart from header and footer (in both the thumbnail in the Print dialog and when printed). This was an issue that was fixed previously (#40), but it seems to be back. Running Monterey and latest Fastmate if that makes any difference.

**Comment by joelekstrom** [comment]
Hi, thanks for the bug report. This seems to be because Fastmail has changed the way they display inline PDF's, so Fastmate can no longer tell by the URL that a PDF is being viewed, unfortunately. Will need to investigate further to see if there's any reasonable way to fix this

**Comment by joelekstrom** [comment]
I made an attempt to fix it, can you see if this build solves the issue for you? For me, all PDF printing is broken from Fastmail right now, even on the web UI both in Safari and Chrome, so I think they may have some issues too.

[Fastmate-1.8.2-beta.zip](https://github.com/joelekstrom/fastmate/files/8008374/Fastmate-1.8.2-beta.zip)

**Comment by sddgit** [comment]
Yeh, 1.8.2 now behaves the same as web UI in Safari - just shows and prints the top 1/3rd of the page. I didn't realise Safari version was broken too!

**Comment by joelekstrom** [comment]
Great, thanks! It sounds like 1.8.2 should solve the inital issue at least, let's wait a bit and see what Fastmail replies before I ship an updated version. The change in 1.8.2 uses the Safari print functionality just like Fastmail web, so it would have the same issues that the website has.. Previously Fastmate would print PDF's manually by checking the current URL which is no longer possible.

**Comment by joelekstrom** [comment]
Yep. Have the same issue in both Safari and Chrome (and Fastmate). I got the same answer to my report but sent them this thread and they said they have forwarded it to their developers now 👍

**Comment by sddgit** [comment]
Got this response:

“ Our developers have been able to reproduce this, but I'm afraid there is not a timeline as to when they will be able to fix this for all users. It is contained within a list of known issues to work on. ”

**Comment by joelekstrom** [comment]
Yeah, got something similar. That's good! Perhaps I should ship 1.8.2 so Fastmate is ready to print when the time comes

**Comment by sddgit** [comment]
Yes, I think that’d probably worthwhile. Maybe with the new icon discussed in issue #39? 😉

**Comment by joelekstrom** [comment]
Hi again @sddgit! Here's a release candidate for 1.8.2 (with new icon too!) I'd love if you could help me test your cases a bit more before I roll it out.

I changed the logic a bit so that it now uses two different ways of printing:
1. If it _thinks_ an attachment is open (it's just an educated guess since Fastmail moved to anonymised file names) it uses the "modern" WKWebView system to print, otherwise it uses:
2. A legacy, deprecated way of printing with WebView (that it has used up until now). However, the "modern" way is not very good, and does not allow customising headers or footers, so I prefer this legacy way and it will try to use it whenever it can.

Since Fastmate can no longer determine what type of attachment is open because of anonymised file names, it attempts the modern way of printing since that can handle PDF attachments internally.

This covers most printing cases (I hope). However, Fastmail is still having problems printing PDF's so they're still gonna be broken in Fastmate too. 

[Fastmate.zip](https://github.com/joelekstrom/fastmate/files/8039054/Fastmate.zip)

**Comment by sddgit** [comment]
Thanks for that. I will test asap. Shouldn’t be too long…

Regards, 

Steve

**Comment by joelekstrom** [comment]
That helps a lot! Thank you!

**Comment by joelekstrom** [comment]
Fixed in [v1.8.2](https://github.com/joelekstrom/fastmate/releases/tag/v1.8.2)
